export const UPDATE_SCROLL_POSITION = 'UPDATE_SCROLL_POSITION'
export const TOGGLE_CURRENT_PAGE_HASSCROLL = 'TOGGLE_CURRENT_PAGE_HASSCROLL'
export const HIDE_NAV_BAR = 'HIDE_NAV_BAR'
export const SHOW_NAV_BAR = 'SHOW_NAV_BAR'
